defaults:
  - /model/base
  - _self_

model:
  BERT:
    _target_: "trax.models.BERT"
    head: "${model.BERTMLMHead}"
  BERTMLMHead:
    _target_: "trax.models.research.bert.BERTMLMHead"
    _partial_: true
