# Katalogi do pominięcia
exclude = [
    ".git", ".venv", "venv", "build", "dist", ".ipynb_checkpoints", "node_modules", "site-packages"
]

extend-include = ["*.ipynb"]

line-length = 88
indent-width = 4

# Python 3.12
target-version = "py312"

[lint]
select = ["E4", "E7", "E9", "F", "I", "W"]  # F401 + sortowanie importów (I)
ignore = ["E302"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = []
known-third-party = []
lines-between-types = 1

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
