train:
  train:
    eval_frequency: 500
    eval_steps: 10
    model: "${model.ConfigurableTerraformer}"
    steps: 1000000
    optimizer: "${optim.Adafactor}"
    use_memory_efficient_trainer: true
    inputs: "${data.make_streams}"
