train:
  train:
    eval_frequency: 1000
    eval_steps: 10
    model: "${model.ConfigurableTerraformer}"
    steps: 524288
    optimizer: "${optim.Adafactor}"
    use_memory_efficient_trainer: false
