defaults:
  - /model/base
  - _self_

model:
  Reformer:
    _target_: "trax.models.Reformer"
    _partial_: true
    d_model: 1024
    d_ff: 4096
    dropout: 0.3
    ff_activation: "${model.Relu}"
    ff_dropout: 0.1
    max_len: 2048
    n_heads: 16
    n_encoder_layers: 6
    n_decoder_layers: 6
    input_vocab_size: 33300
