defaults:
  - base
  - _self_

schedule:
  warmup_and_rsqrt_decay:
    _target_: "trax.learning.supervised.lr_schedules.warmup_and_rsqrt_decay"
    _partial_: true
    max_value: 0.01
    n_warmup_steps: 1000
