optim:
  Adafactor:
    _target_: "trax.optimizers.Adafactor"
    _partial_: true
    weight_decay_rate: 1e-05
    weight_decay_n_steps: 100000
    beta1: 0.0
    decay_rate: 0.8
    clipping_threshold: 1.0
    epsilon1: 1e-16
    epsilon2: 0.001
    factored: true
    multiply_by_parameter_scale: true
