defaults:
  - base
  - _self_

optim:
  Adafactor:
    _partial_: true
    beta1: 0.0
    decay_rate: 0.8
    clipping_threshold: 1.0
    epsilon1: 1e-16
    epsilon2: 0.001
    factored: true
    multiply_by_parameter_scale: true
