ckpt:
  ckpt:
    checkpoints_at:
      - 1000
      - 5000
      - 10000
      - 20000
      - 40000
      - 60000
      - 80000
      - 100000
      - 200000
      - 300000
      - 400000
      - 500000
    permanent_checkpoints_at:
      - 100000
      - 150000
      - 200000
      - 250000
      - 300000
      - 350000
