model:
  RNNLM:
    _target_: "trax.models.RNNLM"
    _partial_: true
    rnn_cell: "${model.LSTMCell}"
    rnn_cell_d_state_multiplier: 2
    d_model: 512
    dropout: 0.1
    n_layers: 2
    vocab_size: 32000
  LSTMCell:
    _target_: "trax.layers.LSTMCell"
    _partial_: true
