model:
  bair_robot_pushing_hparams:
    _target_: "trax.models.bair_robot_pushing_hparams"
    video_num_input_frames: 1
    video_num_target_frames: 1
  SelfAttention:
    _target_: "trax.layers.SelfAttention"
    _partial_: true
    chunk_len: 512
    n_chunks_before: 1
  ReformerLM:
    _target_: "trax.models.ReformerLM"
    _partial_: true
    attention_type: "${model.SelfAttention}"
    d_attention_key: 64
    d_attention_value: 64
    d_model: 512
    d_ff: 2048
    dropout: 0.0
    ff_activation: "${model.FastGelu}"
    max_len: 24576
    n_heads: 4
    n_layers: 3
    vocab_size: 256
    pos_axial_shape: "(2, 64, 64, 3)"
    pos_d_axial_embs: "(128, 128, 128, 128)"
  attn_type:
    _target_: "trax.models.attn_type"
  FastGelu:
    _target_: "trax.layers.FastGelu"
    _partial_: true
