model:
  Reformer:
    _target_: "trax.models.Reformer"
    _partial_: true
    d_model: 512
    d_ff: 2048
    dropout: 0.1
    ff_activation: "${model.Relu}"
    ff_dropout: 0.1
    max_len: 2048
    n_heads: 8
    n_encoder_layers: 6
    n_decoder_layers: 6
    input_vocab_size: 33300
  Relu:
    _target_: "trax.layers.Relu"
    _partial_: true
