defaults:
  - base
  - _self_

model:
  TransformerLM:
    _target_: "trax.models.TransformerLM"
    _partial_: true
    d_model: 1024
    d_ff: 8192
    dropout: 0.1
    max_len: 2048
    n_heads: 8
    n_layers: 8
    vocab_size: 32000
