defaults:
  - base
  - _self_

model:
  TransformerEncoder:
    _target_: "trax.models.TransformerEncoder"
    _partial_: true
    d_model: 512
    d_ff: 2048
    dropout: 0.1
    max_len: 512
    n_classes: 2
    n_heads: 8
    n_layers: 6
    vocab_size: 32000
