defaults:
  - base
  - _self_

model:
  TransformerLM:
    _target_: "trax.models.TransformerLM"
    _partial_: true
    d_model: 512
    d_ff: 2048
    dropout: 0.1
    max_len: 4096
    n_heads: 8
    n_layers: 6
    vocab_size: 33300
