train:
  BERTPretrainingLoss:
    _target_: "trax.models.research.bert.BERTPretrainingLoss"
  train:
    loss_fn: "${train.BERTPretrainingLoss}"
    metrics:
      loss: "${train.BERTPretrainingLoss}"
